module.exports = {
  User: require('./User'),
  Customer: require('./Customer'),
  Category: require('./Category'),
  Product: require('./Product'),
  Order: require('./Order'),
  Counter: require('./Counter'),
  CreditTransaction: require('./CreditTransaction'),
  InventoryTransaction: require('./InventoryTransaction'),
  Expense: require('./Expense'),
  BusinessSettings: require('./BusinessSettings'),
  Table: require('./Table'),
  AuditLog: require('./AuditLog'),
  Feedback: require('./Feedback'),
};
